Some changes made to make shellcheck good

diff --git a/0x05-processes_and_signals/101-manage_my_process b/0x05-processes_and_signals/101-manage_my_process
--- a/0x05-processes_and_signals/101-manage_my_process
+++ b/0x05-processes_and_signals/101-manage_my_process
@@ -1,6 +1,17 @@
 #!/usr/bin/env bash
 #Bash script that creates a subprocess
-. /lib/lsb/init-functions
+#. /lib/lsb/init-functions
+
+INIT_FUNCTIONS="/lib/lsb/init-functions"
+
+#check if the file exoists
+if [ ! -e "$INIT_FUNCTIONS" ]; then
+	echo "Error: $INIT_FUNCTIONS not found." >$2
+	exit 1
+fi
+
+#Source the init-functions file
+. "$INIT_FUNCTIONS"
 
 PIDFILE=/var/run/my_process.pid
 
